CWIN:
  name:
    - SUPER FREE
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

C18:
  name:
    - myTV SUPER 18台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

JUHD:
  name:
    - 翡翠台(超高清)
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

TVG:
  name:
    - 黃金翡翠台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

J:
  name:
    - 翡翠台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

B:
  name:
    - TVB Plus
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

C:
  name:
    - 無綫新聞台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

P:
  name:
    - 明珠台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTVC:
  name:
    - 千禧經典台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTVS:
  name:
    - 亞洲劇台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CDR3:
  name:
    - 華語劇台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

TVO:
  name:
    - 黃金華劇台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTVE:
  name:
    - 娛樂新聞台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CCOC:
  name:
    - 戲曲台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

KID:
  name:
    - SUPER Kids Channel
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

ZOO:
  name:
    - ZooMoo
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CNIKO:
  name:
    - Nickelodeon
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CNIJR:
  name:
    - Nick Jr
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CCLM:
  name:
    - 粵語片台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CMAM:
  name:
    - 美亞電影台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTHR:
  name:
    - Thrill
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CCCM:
  name:
    - 天映經典頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CMC:
  name:
    - 中國電影頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CRTX:
  name:
    - ROCK Action
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

POPC:
  name:
    - PopC
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CKIX:
  name:
    - KIX
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

LNH:
  name:
    - Love Nature HD
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

LN4:
  name:
    - Love Nature 4K
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

GEM:
  name:
    - GEM
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

SMS:
  name:
    - Global Trekker
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CRTE:
  name:
    - ROCK綜藝娛樂
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CAXN:
  name:
    - AXN
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CANI:
  name:
    - Animax
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CJTV:
  name:
    - tvN
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTS1:
  name:
    - 無線衛星亞洲台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CRE:
  name:
    - 創世電視
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

FBX:
  name:
    - FashionBox
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CMEZ:
  name:
    - Mezzo Live HD
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CC1:
  name:
    - 中央電視台綜合頻道 (港澳版)
    - CCTV-1
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CGD:
  name:
    - CGTN (中國環球電視網)記錄頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CGE:
  name:
    - CGTN (中國環球電視網)英語頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

DTV:
  name:
    - 東方衛視國際頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

PCC:
  name:
    - 鳳凰衛視中文台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

PIN:
  name:
    - 鳳凰衛視資訊台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

PHK:
  name:
    - 鳳凰衛視香港台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CMN1:
  name:
    - 神州新聞台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CTSN:
  name:
    - 無線衛星新聞台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CCNA:
  name:
    - 亞洲新聞台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CJAZ:
  name:
    - 半島電視台英語頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CF24:
  name:
    - France 24
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CDW1:
  name:
    - DW
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CNHK:
  name:
    - NHK World-Japan
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

CARI:
  name:
    - Arirang TV
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

EVT1:
  name:
    - myTV SUPER直播足球1台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

EVT2:
  name:
    - myTV SUPER直播足球2台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

EVT3:
  name:
    - myTV SUPER直播足球3台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2


EVT4:
  name:
    - myTV SUPER直播足球4台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

EVT5:
  name:
    - myTV SUPER直播足球5台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

EVT6:
  name:
    - myTV SUPER直播足球6台
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2

TEST:
  name:
    - 測試頻道
  scraper:
    mytvsuper: 
  refresh: once
  recap: 7
  preview: 2
