J:
  name:
    - 翡翠台
    - 翡翠台(超高清)
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

CWIN:
  name:
    - SUPER FREE
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

C28:
  name:
    - 28AI智慧賽馬
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

TVG:
  name:
    - 黃金翡翠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

B:
  name:
    - TVB Plus
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

C:
  name:
    - 無綫新聞台
    - 互動窗 1
    - 互動窗 2
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

P:
  name:
    - 明珠台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0


CTVE:
  name:
    - 娛樂新聞台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

CMAM:
  name:
    - 美亞電影台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

POPC:
  name:
    - PopC
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

CRE:
  name:
    - 創世電視
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

CC1:
  name:
    - 中央電視台綜合頻道 (港澳版)
    - CCTV-1
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

PCC:
  name:
    - 鳳凰衛視中文台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

PIN:
  name:
    - 鳳凰衛視資訊台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0

PHK:
  name:
    - 鳳凰衛視香港台
  scraper:
    mytvsuper: 
  refresh: today
  recap: 7
  preview: 0
