name = "epg-updater-trigger"
main = "trigger.js"
compatibility_date = "2025-02-15"
workers_dev = false

account_id = "99475a57aed1c75f9d942f99b7adf379"  # 从 Cloudflare 帐户中获取
zone_id = "cbcc0b2a72d03e089a4a8ba1b30301ec"  # 从域名概述页获取
